### ISSUE TITLE
Fetch API cannot load file

### ISSUE THREAD

**Issue by thadeuszlay** [lordpoint/wasm-demo#2]
Hi,

I get this error when running the code:
```
scripts.js:6 Fetch API cannot load file:///path/to/my/dir/wasm/sampelProject/squarer.wasm. URL scheme must be "http" or "https" for CORS request.
loadWebAssembly @ scripts.js:6
(anonymous) @ scripts.js:14
scripts.js:6 Uncaught (in promise) TypeError: Failed to fetch
    at loadWebAssembly (scripts.js:6)
    at scripts.js:14
loadWebAssembly @ scripts.js:6
(anonymous) @ scripts.js:14
Promise.then (async)
(anonymous) @ scripts.js:14

```

**Comment by suhailvs** [comment]
use `firefox`

**Comment by Gaserd** [comment]
@thadeuszlay 

Hi, you can use https://github.com/kzahel/web-server-chrome and chose a folder for your project. This extension starts a web server and creates a link local project.

**Comment by Aurathic** [comment]
@Gaserd Is there an equivalent for Firefox?

**Comment by PeterCCLiu** [comment]
This issue still persists in Chrome at 2022. 

```
- Access to fetch at 'file:///Users/pl/wasm-demo/squarer.wasm' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
- Failed to load resource: net::ERR_FAILED
- Uncaught (in promise) TypeError: Failed to fetch
    at loadWebAssembly (scripts.js:4:10)
    at scripts.js:10:1
```
